services:
  app:
    build: .
    ports:
      - "8083:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PositiveStudentManagement;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge
