services:
  app:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - "8084:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PositiveStudentManagement;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
    networks:
      - app-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1436:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ../Database/Scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge
